[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "my_rust_lib"